; CNN inference configuration
[cnn]
model_path=models/rfdetr.onnx
input_width=560
input_height=560
score_threshold=0.65
mask_threshold=0.5
score_activation=sigmoid
exclude_last_class=false
clip_masks_to_boxes=false
